---
title: "PROJECT TITLE"
author: "LAW students"
date: "Mar. 29th"
output: github_document
---

### Load packages

```{r load-packages, message=FALSE}
library(tidyverse) 
library(broom)
library(infer)
```

### Load data
```{r load-data, message=FALSE}
students <- read_csv("/cloud/project/proposal/student-mat.csv")
```
## Section 1. Introduction

## Section 2. Data analysis plan

```{r}
students <- students %>%
  mutate(first_gen = case_when(
    Medu < 4 ~ "Yes",
    Fedu < 4 ~ "Yes",
    Medu == 4 ~ "No",
    Fedu == 4 ~ "No"))
students %>%
  count(first_gen)
```

```{r avg-score}
students <- students %>%
  mutate(avg_score = ((G1 + G2 + G3)/3))
```

```{r backward-selection}
full_model <- lm(avg_score ~ school + 
                  sex + age + address + 
                  famsize + Pstatus + 
                   Mjob + Fjob + 
                  reason + guardian + traveltime +
                  studytime + failures + 
                  paid + activities +
                  nursery + higher + internet +
                  romantic + famrel + freetime +
                  goout + Dalc + Walc +
                  health + absences + first_gen, data = students)
final_model <- step(full_model, direction = "backward")
tidy(final_model) %>% 
  select(term, estimate)
```


```{r hist}
students %>% 
  group_by(first_gen) %>%
  summarise(median = median(studytime), IQR = IQR(studytime))
```
```{r}
students %>%
  group_by(first_gen) %>%
  summarise (med=median(avg_score),
             IQR = IQR(avg_score))
```

```{r}
students %>%
  count(sex)
```


```{r}
ggplot (students, mapping = aes(x = first_gen, y = avg_score)) +
  geom_boxplot() + 
  labs(title = "Distribution of Study Time in First Generation Students", x = "First Generation", y = "Frequency") + theme_light()
```

```{r}
ggplot (students, mapping = aes(x = sex, y = avg_score)) +
  geom_boxplot() + 
  labs(title = "Distribution of Study Time in First Generation Students", x = "First Generation", y = "Frequency") + theme_light()
```


```{r hist-studytime}
ggplot (data = students) +
  geom_bar(mapping = aes(x = first_gen, fill = as.character(studytime)), position = "fill") + 
  labs(title = "Distribution of Study Time in First Generation Students", x = "First Generation", y = "proportion of different study time", fill = "Study Time") 
```
```{r}
students
```

```{r hist-goout}
ggplot(data = students, mapping = aes(x = goout, y = avg_score, fill = first_gen)) +
  geom_bar(stat = "Identity", position = position_dodge()) + 
  labs(title = "Average Score vs. Going Out", subtitle = "in First and non-First Generation Students", x = "Going Out", y = "Average Score", fill = "First Generation")
```

study time 
go out 
family size 
mother's job 

```{r hist2}
ggplot(data = students, mapping = aes(x = studytime, y = avg_score, fill = first_gen)) +
  geom_bar(stat = "Identity", position = position_dodge()) + 
  labs(title = "Average Score vs. Study Time", subtitle = "in First and non-First Generation Students", x = "Study Time", y = "Average Score", fill = "First Generation")
```
```{r}

```

## Section 3. Data